/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.switchon.wizards.panels;

import de.cismet.cids.custom.switchon.utils.Taggroups;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.CidsBeanStore;
import de.cismet.cids.dynamics.Disposable;

/**
 * DOCUMENT ME!
 *
 * @author   Gilles Baatz
 * @version  $Revision$, $Date$
 */
public class BasicInformationVisualPanel extends javax.swing.JPanel implements CidsBeanStore, Disposable {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            BasicInformationVisualPanel.class);

    //~ Instance fields --------------------------------------------------------

    private Taggroups typeTaggroup;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected de.cismet.cids.custom.switchon.objecteditors.BasicPropertiesPanel basicPropertiesPanel;
    protected de.cismet.cids.custom.switchon.gui.InfoBoxPanel infoBoxPanel;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form BasicResourcePropertiesVisualPanel.
     *
     * @deprecated  Constructor for Netbeans
     */
    public BasicInformationVisualPanel() {
        this(Taggroups.META_DATA_TYPE);
        LOG.warn("Do not use this constructor, it is only there for the Netbeans GUI editor.", new Exception());
    }

    /**
     * Creates new form BasicResourcePropertiesVisualPanel.
     *
     * @param  typeTaggroup  DOCUMENT ME!
     */
    public BasicInformationVisualPanel(final Taggroups typeTaggroup) {
        this.typeTaggroup = typeTaggroup;
        initComponents();
        basicPropertiesPanel.setInfoReceiver(infoBoxPanel);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        basicPropertiesPanel = new de.cismet.cids.custom.switchon.objecteditors.BasicPropertiesPanel(typeTaggroup);
        infoBoxPanel = new de.cismet.cids.custom.switchon.gui.InfoBoxPanel();

        addFocusListener(new java.awt.event.FocusAdapter() {

                @Override
                public void focusGained(final java.awt.event.FocusEvent evt) {
                    formFocusGained(evt);
                }
            });
        setLayout(new java.awt.GridBagLayout());

        basicPropertiesPanel.setVisibleGenerateUUID(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(basicPropertiesPanel, gridBagConstraints);

        infoBoxPanel.setMinimumSize(new java.awt.Dimension(134, 55));
        infoBoxPanel.setPreferredSize(new java.awt.Dimension(748, 55));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        add(infoBoxPanel, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void formFocusGained(final java.awt.event.FocusEvent evt) { //GEN-FIRST:event_formFocusGained
    }                                                                   //GEN-LAST:event_formFocusGained

    @Override
    public CidsBean getCidsBean() {
        return basicPropertiesPanel.getCidsBean();
    }

    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        basicPropertiesPanel.setCidsBean(cidsBean);
    }

    @Override
    public void dispose() {
        basicPropertiesPanel.dispose();
    }
}
